### ISSUE TITLE
Make data:value a generic rdf:Property rather than an owl:DatatypeProperty

### ISSUE THREAD

**Issue by edmondchuc** [AGLDWG/datatype-ont#1]
It's giving me issues in some IDEs such as TopBraid Composer where I want to use data:value to link to individuals. 

@dr-shorthair

**Comment by dr-shorthair** [comment]
Can you give me a test case. 
`rdf:Property` creates problems in OWLy environments like Protege.

**Comment by edmondchuc** [comment]
Sorry, I missed the `data:vocabulary` property. It will do what I need. 

I originally wanted observation results to use `data:value` to link to literal values as well as to individuals.

**Comment by dr-shorthair** [comment]
https://raw.githubusercontent.com/AGLDWG/datatype-ont/master/images/types.png I hope there is a class here for every scalar value.

**Comment by edmondchuc** [comment]
I think what is there meets our requirements 👍 thanks.
